# Exercise 1: Introduction to Python

## Use Python as a calculator to compute 256 times 256

In [6]:
256 * 256

65536

### Put the strings "Hello" and "World!" in two variables. Concatenate both Strings and print them

In [2]:
hello = "Hello"
world = "World!"
print(hello + world)
print(hello + " " + world)

HelloWorld!
Hello World!


### Create a list that contains the 4 strings "alpha", "beta", "gamma", and "delta". Add "epsilon" to the end of this list

In [9]:
l = ["alpha", "beta", "gamma", "delta"]
l.append("epsilon")

### Create a sublist with the first three elements of this list


In [10]:
l2 = l[:3]
l2

['alpha', 'beta', 'gamma']

### Write a Python program to construct the following pattern using for loops

In [12]:
list (range(1,5)) + list (range (5,0,-1))

[1, 2, 3, 4, 5, 4, 3, 2, 1]

In [13]:
for i in  list (range(1,5)) + list (range (5,0,-1)):
    print ("*" * i)

*
**
***
****
*****
****
***
**
*


### Write a function that takes 3 input parameters and returns product of these values

In [17]:
def my_product (*x):
    result = 1
    for elem in x:
        result = result * elem
    return result

### Write a Python function that takes an int as a parameter and checks if the number is prime or not.

In [18]:
def is_prime (x):
    for n in range (2, x // 2 + 1):
        if x % n == 0:
            return False
    return True

print (is_prime (12))
print (is_prime (13))
print (is_prime (23))
print (is_prime (21))

False
True
True
False


### Use your function to create a list that contains all primes from 2 to 100

In [19]:
def primes_up_to (n):
    result = []
    for x in range (2, n+1):
        if is_prime(x):
            result.append(x)
    return result

primes_up_to(100)

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

### Write a function that simulates dice rolls (6-sided dices)
- Write a function that has the number of dice rolls as the input parameter
- The output is a map with the counts how often each result of a roll (1-6) occurred
- You can use the randomint() function from the random package

In [20]:
import random

def roll (n):
    result = {1:0, 2:0, 3:0, 4:0, 5:0, 6:0}
    for i in range (n):
        r = random.randint(1,6)
        result [r] = result[r] + 1
    return result

roll (60000)

{1: 10124, 2: 9991, 3: 9916, 4: 9911, 5: 10078, 6: 9980}

### Combine two dictionaries by adding values for common keys.
d1 = {'a': 100, 'b': 200, 'c':300}

d2 = {'a': 300, 'b': 200, 'd':400}

Sample output: {'a': 400, 'b': 400, 'd': 400, 'c': 300}

In [22]:
d1 = {'a': 100, 'b': 200, 'c':300}
d2 = {'a': 300, 'b': 200, 'd':400}

In [23]:
d = {}
for k,v in d1.items():
    d [k] = v
for k,v in d2.items():
    if k in d:
        d [k] = d[k] + v
    else:
        d[k] = v
d

{'a': 400, 'b': 400, 'c': 300, 'd': 400}

### Create a list of lists. Then, write a list comprehension that creates a list with the lengths of each (sub)list in the primary list

In [26]:
test_l = [[1,2,3],["a", "b"], [123.5, "a", 44]]
[len(t) for t in test_l]

[3, 2, 3]

### Exceptions

Write your own function *my_division* that gets two variables a and b and returns a divided by b. Catch the ZeroDivisionError that occurs if b equals 0 and return 1 in this case.

How could the same behavior be achieved without catching an exception?

In [27]:
def my_division (a, b):
    try: 
        return a / b
    except:
        return 1

print (my_division (20,5))
print (my_division (20,0))

4.0
1


### File handling

Write a function that gets a letter and the path to a (text-)file on your harddrive as input parameters and computes a list as its output. The list should contain one number for each line. The i-th line shows, how often the given letter occurs in line number i.

In [ ]:
def count_letter (letter, filename):
    result = []
    with open(filename, "r") as f: #r ==> open for reading
        for line in f:
            result.append(line.count(letter))
    return result

### Change please!
In our currency, we have coins with certain values, e.g., (200,100,50,20,10,5,2,1) cents. Write a function that computes the different options to pay a certain amount X with the given set of coins.

In [29]:
#slow, but simple solution:
def pay_options (amount, list_of_coin_values, list_of_used_coins=[]):
    #print (amount, list_of_coin_values, list_of_used_coins)
    result = []
    for i, v in enumerate (list_of_coin_values):
        if amount > v:
            new_used_coins = list_of_used_coins.copy()
            new_used_coins.append(v)
            result.extend (pay_options (amount - v, list_of_coin_values [i:], new_used_coins))
        elif amount == v:
            new_option = list_of_used_coins.copy()
            new_option.append(v)          
            result.append (new_option)
    return result; 

## Numpy

### Create a numpy arrays with 20 rows and 10 columns, all values set to zero

In [3]:
import numpy as np
x = np.zeros ((20,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Create an array with the same shape containing all natural numbers 0-199

In [6]:
np.arange(200).reshape((20,10))

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

### Create a 4-dimensional array with 16 elements and set all values to a random integer smaller than 5

In [5]:
x = np.random.randint(5, size=(2,2,2,2))
x

array([[[[2, 4],
         [1, 1]],

        [[0, 2],
         [0, 2]]],


       [[[1, 1],
         [3, 1]],

        [[2, 3],
         [3, 1]]]])

### What is the mean of all values contained in this array?

In [10]:
x.mean()

2.1875

### Select a sub-array containing exactly two elements of that array

In [22]:
x[:,1,1,1]

array([2, 1])

### Given a numpy array, return a new numpy array the contains only the elements that are greater than 100

In [ ]:
x = np.array([120,-5,150,250,300,50,112])
x[x > 100]