# Exercise 1: Introduction to Python

### Use Python as a calculator to compute 256²

In [1]:
256**2

65536

### Put the strings "Hello" and "World!" in two variables. Concatenate both Strings and print them

In [2]:
hello = "Hello"
world = "World!"

print(hello + ", " + world)

Hello, World!


### Create a list that contains the 4 strings "alpha", "beta", "gamma", and "delta". Add "epsilon" to the end of this list

In [3]:
ls = ["alpha", "beta", "gamma", "delta"]
ls.append("epsilon")
ls

['alpha', 'beta', 'gamma', 'delta', 'epsilon']

### Create a sublist with the first three elements of this list


In [4]:
ls[:3]

['alpha', 'beta', 'gamma']

### Write a Python program to construct the following pattern using for loops

In [5]:
* 
* * 
* * * 
* * * * 
* * * * * 
* * * * 
* * * 
* * 
*

SyntaxError: invalid syntax (<ipython-input-5-fe62e6fde7e8>, line 1)

In [6]:
for i in range(6):
    print("* " * i)
for i in reversed(range(5)):
    print("* " * i)


* 
* * 
* * * 
* * * * 
* * * * * 
* * * * 
* * * 
* * 
* 



### Write a function that takes 3 input parameters and returns the product of these values

In [7]:
def f(a, b, c):
    return a*b*c
    
f(1,2,3)

6

### Write a Python function that takes an int as a parameter and checks if the number is prime or not.

In [8]:
import math

def is_prime(x: int):
    for i in range(2, (int)(math.sqrt(x)) + 1):
        if x % i == 0:
            return False
    return x != 1
    
# test:
is_prime(97) and not is_prime(17*19) and not is_prime(1)

True

### Use your function to create a list that contains all primes from 2 to 100

In [9]:
[i for i in filter(is_prime, range(2, 100))]

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

### Write a function that simulates dice rolls (6-sided dices)
- Write a function that has the number of dice rolls as the input parameter
- The output is a map with the counts how often each result of a roll (1-6) occurred
- You can use the randomint() function from the random package

In [10]:
import random

def dice(roll_count: int):
    rolls = [ random.randint(1,6) for _ in range(roll_count) ]
    
    return { i: rolls.count(i) for i in range(1,7) }
  
dice(100)

{1: 19, 2: 18, 3: 16, 4: 19, 5: 14, 6: 14}

### Combine two dictionaries by adding values for common keys.
d1 = {'a': 100, 'b': 200, 'c':300}

d2 = {'a': 300, 'b': 200, 'd':400}

Sample output: {'a': 400, 'b': 400, 'd': 400, 'c': 300}

In [11]:
def dict_sum(d1, d2):
    all_keys = d1.keys() | d2.keys()
    
    return { k: d1.get(k, 0) + d2.get(k, 0) for k in all_keys }


d1 = {'a': 100, 'b': 200, 'c':300}
d2 = {'a': 300, 'b': 200, 'd':400}

dict_sum(d1, d2)

{'c': 300, 'd': 400, 'b': 400, 'a': 400}

### Create a list of lists. Then, write a list comprehension that creates a list with the lengths of each (sub)list in the primary list

In [12]:
super_list = [ [1], [2,2], [4,4,4,4], [3,3,3], [8,8,8,8,8,8,8,8] ]

[ len(sub_list) for sub_list in super_list ]

[1, 2, 4, 3, 8]

### Exceptions

Write your own function *my_division* that gets two variables a and b and returns a divided by b. Catch the ZeroDivisionError that occurs if b equals 0 and return 1 in this case.

How could the same behavior be achieved without catching an exception?

In [13]:
def my_division(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        return 1
    
    
my_division(7, 0)

1

### File handling

Write a function that gets a letter and the path to a (text-)file on your harddrive as input parameters and computes a list as its output. The list should contain one number for each line. The i-th line shows, how often the given letter occurs in line number i.

In [14]:
def count_per_line(letter, file_path):
    file = open(file_path, "r")
    
    return [ line.count(letter) for line in file ]

count_per_line("d", "./some-file-with-data.txt")

[2, 1, 1, 0, 0, 1, 0, 0, 1, 0, 4, 1, 0, 0]

### Change please!
In our currency, we have coins with certain values, e.g., (200,100,50,20,10,5,2,1) cents. Write a function that computes the different options to pay a certain amount X with the given set of coins.

In [19]:
def pay_options(amount, values, candidate = []):
    if len(values) == 0:
        return []
    else:
        first, *rest = values
        
        results1 = pay_options(amount, rest, candidate)

        new_candidate = [*candidate, first]
        
        if sum(new_candidate) > amount:
            return results1
        elif sum(new_candidate) < amount:
            results2 = pay_options(amount, values, new_candidate)
            return results1 + results2
        else:
            return [*results1, new_candidate]
            

pay_options(10, [200,100,50,20,10,5,2,1])

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [2, 1, 1, 1, 1, 1, 1, 1, 1],
 [2, 2, 1, 1, 1, 1, 1, 1],
 [2, 2, 2, 1, 1, 1, 1],
 [2, 2, 2, 2, 1, 1],
 [2, 2, 2, 2, 2],
 [5, 1, 1, 1, 1, 1],
 [5, 2, 1, 1, 1],
 [5, 2, 2, 1],
 [5, 5],
 [10]]

## Numpy

### Create a numpy array with 20 rows and 10 columns, where all values are set to zero

In [14]:
import numpy

array = numpy.zeros((20,10))

print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Create an array with the same shape containing all natural numbers 0-199

In [3]:
import numpy

array = numpy.arange(0,200).reshape(20,10)

print(array)

[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]


### Create a 4-dimensional array with exactly 16 elements and set all values to a random integer smaller than 5

In [10]:
rng = numpy.random.default_rng() 
array = rng.integers(0, 5, (4,4))

print(array)

[[1 4 3 0]
 [3 1 0 4]
 [2 1 3 1]
 [1 4 4 4]]


### What is the mean of all values contained in this array?

In [18]:
numpy.mean(array)

74.6875

### Select a sub-array containing exactly two elements of that array!

In [12]:
array[1:3]

array([[3, 1, 0, 4],
       [2, 1, 3, 1]])

### Given a numpy array, return a new numpy array that contains only the elements that are greater than 100

In [46]:
rng = numpy.random.default_rng() 
array = rng.integers(0, 200, (4,4))
array = numpy.extract(array > 100, array)

print(array)

[174 191 116 114 197 172 148 155]
